// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package database

import (
	"time"
)

type Post struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Message   string
	AuthorID  string
	UserID    string
}

type User struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	FirstName string
	LastName  string
	Email     string
	Username  string
	ApiKey    string
}
