// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: users.sql

package database

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, created_at, updated_at, first_name, last_name, email, sid) 
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at, first_name, last_name, email, sid
`

type CreateUserParams struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	FirstName string
	LastName  string
	Email     string
	Sid       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Sid,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Sid,
	)
	return i, err
}

const getUserByFirstname = `-- name: GetUserByFirstname :one
SELECT id, created_at, updated_at, first_name, last_name, email, sid FROM users WHERE first_name=?
`

func (q *Queries) GetUserByFirstname(ctx context.Context, firstName string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByFirstname, firstName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Sid,
	)
	return i, err
}
